name: bokia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.1
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  pretty_dio_logger: ^1.4.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/welcome.png
    - assets/splach_logo.png
